//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.04 at 12:30:41 上午 CST 
//


package amazclient.xmlmodel;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AmazonMaturityRatingType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AmazonMaturityRatingType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="adult_content"/>
 *     &lt;enumeration value="ages_13_and_older"/>
 *     &lt;enumeration value="ages_17_and_older"/>
 *     &lt;enumeration value="ages_9_and_older"/>
 *     &lt;enumeration value="all_ages"/>
 *     &lt;enumeration value="children"/>
 *     &lt;enumeration value="rating_pending"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AmazonMaturityRatingType")
@XmlEnum
public enum AmazonMaturityRatingType {

    @XmlEnumValue("adult_content")
    ADULT_CONTENT("adult_content"),
    @XmlEnumValue("ages_13_and_older")
    AGES_13_AND_OLDER("ages_13_and_older"),
    @XmlEnumValue("ages_17_and_older")
    AGES_17_AND_OLDER("ages_17_and_older"),
    @XmlEnumValue("ages_9_and_older")
    AGES_9_AND_OLDER("ages_9_and_older"),
    @XmlEnumValue("all_ages")
    ALL_AGES("all_ages"),
    @XmlEnumValue("children")
    CHILDREN("children"),
    @XmlEnumValue("rating_pending")
    RATING_PENDING("rating_pending");
    private final String value;

    AmazonMaturityRatingType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AmazonMaturityRatingType fromValue(String v) {
        for (AmazonMaturityRatingType c: AmazonMaturityRatingType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
