//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.04 at 12:30:41 上午 CST 
//


package amazclient.xmlmodel;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BluRayRegionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BluRayRegionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="region_a"/>
 *     &lt;enumeration value="region_b"/>
 *     &lt;enumeration value="region_c"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BluRayRegionType")
@XmlEnum
public enum BluRayRegionType {

    @XmlEnumValue("region_a")
    REGION_A("region_a"),
    @XmlEnumValue("region_b")
    REGION_B("region_b"),
    @XmlEnumValue("region_c")
    REGION_C("region_c");
    private final String value;

    BluRayRegionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BluRayRegionType fromValue(String v) {
        for (BluRayRegionType c: BluRayRegionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
