//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.04 at 12:30:41 上午 CST 
//


package amazclient.xmlmodel;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FulfillReadiness.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FulfillReadiness">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="drop_ship_ready"/>
 *     &lt;enumeration value="not_ready"/>
 *     &lt;enumeration value="receive_ready"/>
 *     &lt;enumeration value="exception_receive_ready"/>
 *     &lt;enumeration value="po_ready"/>
 *     &lt;enumeration value="unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FulfillReadiness")
@XmlEnum
public enum FulfillReadiness {

    @XmlEnumValue("drop_ship_ready")
    DROP_SHIP_READY("drop_ship_ready"),
    @XmlEnumValue("not_ready")
    NOT_READY("not_ready"),
    @XmlEnumValue("receive_ready")
    RECEIVE_READY("receive_ready"),
    @XmlEnumValue("exception_receive_ready")
    EXCEPTION_RECEIVE_READY("exception_receive_ready"),
    @XmlEnumValue("po_ready")
    PO_READY("po_ready"),
    @XmlEnumValue("unknown")
    UNKNOWN("unknown");
    private final String value;

    FulfillReadiness(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FulfillReadiness fromValue(String v) {
        for (FulfillReadiness c: FulfillReadiness.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
