//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.04 at 12:30:41 上午 CST 
//


package amazclient.xmlmodel;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LengthUnitOfMeasure.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LengthUnitOfMeasure">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="MM"/>
 *     &lt;enumeration value="CM"/>
 *     &lt;enumeration value="M"/>
 *     &lt;enumeration value="IN"/>
 *     &lt;enumeration value="FT"/>
 *     &lt;enumeration value="inches"/>
 *     &lt;enumeration value="feet"/>
 *     &lt;enumeration value="meters"/>
 *     &lt;enumeration value="decimeters"/>
 *     &lt;enumeration value="centimeters"/>
 *     &lt;enumeration value="millimeters"/>
 *     &lt;enumeration value="micrometers"/>
 *     &lt;enumeration value="nanometers"/>
 *     &lt;enumeration value="picometers"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LengthUnitOfMeasure")
@XmlEnum
public enum LengthUnitOfMeasure {

    MM("MM"),
    CM("CM"),
    M("M"),
    IN("IN"),
    FT("FT"),
    @XmlEnumValue("inches")
    INCHES("inches"),
    @XmlEnumValue("feet")
    FEET("feet"),
    @XmlEnumValue("meters")
    METERS("meters"),
    @XmlEnumValue("decimeters")
    DECIMETERS("decimeters"),
    @XmlEnumValue("centimeters")
    CENTIMETERS("centimeters"),
    @XmlEnumValue("millimeters")
    MILLIMETERS("millimeters"),
    @XmlEnumValue("micrometers")
    MICROMETERS("micrometers"),
    @XmlEnumValue("nanometers")
    NANOMETERS("nanometers"),
    @XmlEnumValue("picometers")
    PICOMETERS("picometers");
    private final String value;

    LengthUnitOfMeasure(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LengthUnitOfMeasure fromValue(String v) {
        for (LengthUnitOfMeasure c: LengthUnitOfMeasure.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
