//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.04 at 12:30:41 上午 CST 
//


package amazclient.xmlmodel;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NoiseLevelUnitOfMeasure.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NoiseLevelUnitOfMeasure">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="dBA"/>
 *     &lt;enumeration value="decibels"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "NoiseLevelUnitOfMeasure")
@XmlEnum
public enum NoiseLevelUnitOfMeasure {

    @XmlEnumValue("dBA")
    D_BA("dBA"),
    @XmlEnumValue("decibels")
    DECIBELS("decibels");
    private final String value;

    NoiseLevelUnitOfMeasure(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NoiseLevelUnitOfMeasure fromValue(String v) {
        for (NoiseLevelUnitOfMeasure c: NoiseLevelUnitOfMeasure.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
