//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.04 at 12:30:41 上午 CST 
//


package amazclient.xmlmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IsRecalled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="RecallDescription">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *               &lt;maxLength value="1500"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "isRecalled",
    "recallDescription"
})
@XmlRootElement(name = "Recall")
public class Recall {

    @XmlElement(name = "IsRecalled")
    protected boolean isRecalled;
    @XmlElement(name = "RecallDescription", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String recallDescription;

    /**
     * Gets the value of the isRecalled property.
     * 
     */
    public boolean isIsRecalled() {
        return isRecalled;
    }

    /**
     * Sets the value of the isRecalled property.
     * 
     */
    public void setIsRecalled(boolean value) {
        this.isRecalled = value;
    }

    /**
     * Gets the value of the recallDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecallDescription() {
        return recallDescription;
    }

    /**
     * Sets the value of the recallDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecallDescription(String value) {
        this.recallDescription = value;
    }

}
