//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.04 at 12:30:41 上午 CST 
//


package amazclient.xmlmodel;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClothingType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Accessory"/>
 *               &lt;enumeration value="Bag"/>
 *               &lt;enumeration value="Shoes"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VariationData" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Parentage" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="parent"/>
 *                         &lt;enumeration value="child"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Size" type="{}StringNotNull" minOccurs="0"/>
 *                   &lt;element name="Color" type="{}StringNotNull" minOccurs="0"/>
 *                   &lt;element name="VariationTheme" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="Size"/>
 *                         &lt;enumeration value="Color"/>
 *                         &lt;enumeration value="SizeColor"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ClassificationData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CountryOfOrigin" type="{}CountryOfOriginType" minOccurs="0"/>
 *                   &lt;element name="ColorMap" type="{}String" minOccurs="0"/>
 *                   &lt;element name="SizeMap" type="{}StringNotNull" minOccurs="0"/>
 *                   &lt;element name="BeltStyle" type="{}String" minOccurs="0"/>
 *                   &lt;element name="CareInstructions" type="{}String" minOccurs="0"/>
 *                   &lt;element name="ShoeClosureType" type="{}String" minOccurs="0"/>
 *                   &lt;element name="CountryProducedIn" type="{}String" minOccurs="0"/>
 *                   &lt;element name="Department" type="{}StringNotNull" maxOccurs="6" minOccurs="0"/>
 *                   &lt;element name="ExternalTestingCertification" type="{}String" maxOccurs="6" minOccurs="0"/>
 *                   &lt;element name="FabricType" type="{}String" minOccurs="0"/>
 *                   &lt;element name="FabricWash" type="{}String" minOccurs="0"/>
 *                   &lt;element name="HeelHeight" type="{}LengthDimension" minOccurs="0"/>
 *                   &lt;element name="HeelType" type="{}String" minOccurs="0"/>
 *                   &lt;element name="InnerMaterial" type="{}LongString"/>
 *                   &lt;element name="OccasionAndLifestyle" type="{}LongString" maxOccurs="10" minOccurs="0"/>
 *                   &lt;element name="MaterialComposition" type="{}LongString" minOccurs="0"/>
 *                   &lt;element name="MaterialType" type="{}String" minOccurs="0"/>
 *                   &lt;element name="ModelNumber" type="{}StringNotNull" minOccurs="0"/>
 *                   &lt;element name="ModelName" type="{}StringNotNull" minOccurs="0"/>
 *                   &lt;element name="ModelYear" type="{}FourDigitYear" minOccurs="0"/>
 *                   &lt;element name="OuterMaterialType" type="{}HundredString"/>
 *                   &lt;element name="MaterialOpacity" type="{}HundredString" minOccurs="0"/>
 *                   &lt;element name="PatternStyle" type="{}String" minOccurs="0"/>
 *                   &lt;element name="PerformanceRating" type="{}HundredString" maxOccurs="3" minOccurs="0"/>
 *                   &lt;element name="PocketDescription" type="{}String" minOccurs="0"/>
 *                   &lt;element name="Season" type="{}HundredString" minOccurs="0"/>
 *                   &lt;element name="ShaftHeight" type="{}StringLengthOptionalDimension" minOccurs="0"/>
 *                   &lt;element name="ShaftWidth" type="{}StringLengthOptionalDimension" minOccurs="0"/>
 *                   &lt;element name="ShaftDiameter" type="{}StringLengthOptionalDimension" minOccurs="0"/>
 *                   &lt;element name="SpecialSizeType" type="{}String" minOccurs="0"/>
 *                   &lt;element name="SoleMaterial" type="{}LongString"/>
 *                   &lt;element name="SpecialFeatures" type="{}LongString" maxOccurs="2" minOccurs="0"/>
 *                   &lt;element name="SpecificUses" type="{}StringNotNull" maxOccurs="3" minOccurs="0"/>
 *                   &lt;element name="Character" type="{}HundredString" minOccurs="0"/>
 *                   &lt;element name="ToeShape" type="{}HundredString" minOccurs="0"/>
 *                   &lt;element name="WaistSize" type="{}ClothingSizeDimension" minOccurs="0"/>
 *                   &lt;element name="WaistStyle" type="{}String" minOccurs="0"/>
 *                   &lt;element name="WheelType" type="{}String" minOccurs="0"/>
 *                   &lt;element name="WaterResistanceLevel" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="waterproof"/>
 *                         &lt;enumeration value="not_water_resistant"/>
 *                         &lt;enumeration value="water_resistant"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="SafetyWarning" type="{}SuperLongStringNotNull" minOccurs="0"/>
 *                   &lt;element name="ManufacturerWarrantyType" type="{}StringNotNull" minOccurs="0"/>
 *                   &lt;element name="MfrWarrantyDescriptionLabor" type="{}StringNotNull" minOccurs="0"/>
 *                   &lt;element name="MfrWarrantyDescriptionParts" type="{}StringNotNull" minOccurs="0"/>
 *                   &lt;element name="SellerWarrantyDescription" type="{}SuperLongStringNotNull" minOccurs="0"/>
 *                   &lt;element name="NumberOfItems" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *                   &lt;element name="ItemDisplayWeight" type="{}WeightDimension" minOccurs="0"/>
 *                   &lt;element name="ItemDisplayVolume" type="{}VolumeDimension" minOccurs="0"/>
 *                   &lt;element name="ItemDisplayLength" type="{}LengthDimension" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "clothingType",
    "variationData",
    "classificationData"
})
@XmlRootElement(name = "Shoes")
public class Shoes {

    @XmlElement(name = "ClothingType", required = true)
    protected String clothingType;
    @XmlElement(name = "VariationData")
    protected Shoes.VariationData variationData;
    @XmlElement(name = "ClassificationData", required = true)
    protected Shoes.ClassificationData classificationData;

    /**
     * Gets the value of the clothingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClothingType() {
        return clothingType;
    }

    /**
     * Sets the value of the clothingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClothingType(String value) {
        this.clothingType = value;
    }

    /**
     * Gets the value of the variationData property.
     * 
     * @return
     *     possible object is
     *     {@link Shoes.VariationData }
     *     
     */
    public Shoes.VariationData getVariationData() {
        return variationData;
    }

    /**
     * Sets the value of the variationData property.
     * 
     * @param value
     *     allowed object is
     *     {@link Shoes.VariationData }
     *     
     */
    public void setVariationData(Shoes.VariationData value) {
        this.variationData = value;
    }

    /**
     * Gets the value of the classificationData property.
     * 
     * @return
     *     possible object is
     *     {@link Shoes.ClassificationData }
     *     
     */
    public Shoes.ClassificationData getClassificationData() {
        return classificationData;
    }

    /**
     * Sets the value of the classificationData property.
     * 
     * @param value
     *     allowed object is
     *     {@link Shoes.ClassificationData }
     *     
     */
    public void setClassificationData(Shoes.ClassificationData value) {
        this.classificationData = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CountryOfOrigin" type="{}CountryOfOriginType" minOccurs="0"/>
     *         &lt;element name="ColorMap" type="{}String" minOccurs="0"/>
     *         &lt;element name="SizeMap" type="{}StringNotNull" minOccurs="0"/>
     *         &lt;element name="BeltStyle" type="{}String" minOccurs="0"/>
     *         &lt;element name="CareInstructions" type="{}String" minOccurs="0"/>
     *         &lt;element name="ShoeClosureType" type="{}String" minOccurs="0"/>
     *         &lt;element name="CountryProducedIn" type="{}String" minOccurs="0"/>
     *         &lt;element name="Department" type="{}StringNotNull" maxOccurs="6" minOccurs="0"/>
     *         &lt;element name="ExternalTestingCertification" type="{}String" maxOccurs="6" minOccurs="0"/>
     *         &lt;element name="FabricType" type="{}String" minOccurs="0"/>
     *         &lt;element name="FabricWash" type="{}String" minOccurs="0"/>
     *         &lt;element name="HeelHeight" type="{}LengthDimension" minOccurs="0"/>
     *         &lt;element name="HeelType" type="{}String" minOccurs="0"/>
     *         &lt;element name="InnerMaterial" type="{}LongString"/>
     *         &lt;element name="OccasionAndLifestyle" type="{}LongString" maxOccurs="10" minOccurs="0"/>
     *         &lt;element name="MaterialComposition" type="{}LongString" minOccurs="0"/>
     *         &lt;element name="MaterialType" type="{}String" minOccurs="0"/>
     *         &lt;element name="ModelNumber" type="{}StringNotNull" minOccurs="0"/>
     *         &lt;element name="ModelName" type="{}StringNotNull" minOccurs="0"/>
     *         &lt;element name="ModelYear" type="{}FourDigitYear" minOccurs="0"/>
     *         &lt;element name="OuterMaterialType" type="{}HundredString"/>
     *         &lt;element name="MaterialOpacity" type="{}HundredString" minOccurs="0"/>
     *         &lt;element name="PatternStyle" type="{}String" minOccurs="0"/>
     *         &lt;element name="PerformanceRating" type="{}HundredString" maxOccurs="3" minOccurs="0"/>
     *         &lt;element name="PocketDescription" type="{}String" minOccurs="0"/>
     *         &lt;element name="Season" type="{}HundredString" minOccurs="0"/>
     *         &lt;element name="ShaftHeight" type="{}StringLengthOptionalDimension" minOccurs="0"/>
     *         &lt;element name="ShaftWidth" type="{}StringLengthOptionalDimension" minOccurs="0"/>
     *         &lt;element name="ShaftDiameter" type="{}StringLengthOptionalDimension" minOccurs="0"/>
     *         &lt;element name="SpecialSizeType" type="{}String" minOccurs="0"/>
     *         &lt;element name="SoleMaterial" type="{}LongString"/>
     *         &lt;element name="SpecialFeatures" type="{}LongString" maxOccurs="2" minOccurs="0"/>
     *         &lt;element name="SpecificUses" type="{}StringNotNull" maxOccurs="3" minOccurs="0"/>
     *         &lt;element name="Character" type="{}HundredString" minOccurs="0"/>
     *         &lt;element name="ToeShape" type="{}HundredString" minOccurs="0"/>
     *         &lt;element name="WaistSize" type="{}ClothingSizeDimension" minOccurs="0"/>
     *         &lt;element name="WaistStyle" type="{}String" minOccurs="0"/>
     *         &lt;element name="WheelType" type="{}String" minOccurs="0"/>
     *         &lt;element name="WaterResistanceLevel" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="waterproof"/>
     *               &lt;enumeration value="not_water_resistant"/>
     *               &lt;enumeration value="water_resistant"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="SafetyWarning" type="{}SuperLongStringNotNull" minOccurs="0"/>
     *         &lt;element name="ManufacturerWarrantyType" type="{}StringNotNull" minOccurs="0"/>
     *         &lt;element name="MfrWarrantyDescriptionLabor" type="{}StringNotNull" minOccurs="0"/>
     *         &lt;element name="MfrWarrantyDescriptionParts" type="{}StringNotNull" minOccurs="0"/>
     *         &lt;element name="SellerWarrantyDescription" type="{}SuperLongStringNotNull" minOccurs="0"/>
     *         &lt;element name="NumberOfItems" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
     *         &lt;element name="ItemDisplayWeight" type="{}WeightDimension" minOccurs="0"/>
     *         &lt;element name="ItemDisplayVolume" type="{}VolumeDimension" minOccurs="0"/>
     *         &lt;element name="ItemDisplayLength" type="{}LengthDimension" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "countryOfOrigin",
        "colorMap",
        "sizeMap",
        "beltStyle",
        "careInstructions",
        "shoeClosureType",
        "countryProducedIn",
        "department",
        "externalTestingCertification",
        "fabricType",
        "fabricWash",
        "heelHeight",
        "heelType",
        "innerMaterial",
        "occasionAndLifestyle",
        "materialComposition",
        "materialType",
        "modelNumber",
        "modelName",
        "modelYear",
        "outerMaterialType",
        "materialOpacity",
        "patternStyle",
        "performanceRating",
        "pocketDescription",
        "season",
        "shaftHeight",
        "shaftWidth",
        "shaftDiameter",
        "specialSizeType",
        "soleMaterial",
        "specialFeatures",
        "specificUses",
        "character",
        "toeShape",
        "waistSize",
        "waistStyle",
        "wheelType",
        "waterResistanceLevel",
        "safetyWarning",
        "manufacturerWarrantyType",
        "mfrWarrantyDescriptionLabor",
        "mfrWarrantyDescriptionParts",
        "sellerWarrantyDescription",
        "numberOfItems",
        "itemDisplayWeight",
        "itemDisplayVolume",
        "itemDisplayLength"
    })
    public static class ClassificationData {

        @XmlElement(name = "CountryOfOrigin")
        protected String countryOfOrigin;
        @XmlElement(name = "ColorMap")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String colorMap;
        @XmlElement(name = "SizeMap")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String sizeMap;
        @XmlElement(name = "BeltStyle")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String beltStyle;
        @XmlElement(name = "CareInstructions")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String careInstructions;
        @XmlElement(name = "ShoeClosureType")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String shoeClosureType;
        @XmlElement(name = "CountryProducedIn")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String countryProducedIn;
        @XmlElement(name = "Department")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected List<String> department;
        @XmlElement(name = "ExternalTestingCertification")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected List<String> externalTestingCertification;
        @XmlElement(name = "FabricType")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String fabricType;
        @XmlElement(name = "FabricWash")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String fabricWash;
        @XmlElement(name = "HeelHeight")
        protected LengthDimension heelHeight;
        @XmlElement(name = "HeelType")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String heelType;
        @XmlElement(name = "InnerMaterial", required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String innerMaterial;
        @XmlElement(name = "OccasionAndLifestyle")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected List<String> occasionAndLifestyle;
        @XmlElement(name = "MaterialComposition")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String materialComposition;
        @XmlElement(name = "MaterialType")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String materialType;
        @XmlElement(name = "ModelNumber")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String modelNumber;
        @XmlElement(name = "ModelName")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String modelName;
        @XmlElement(name = "ModelYear")
        protected BigInteger modelYear;
        @XmlElement(name = "OuterMaterialType", required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String outerMaterialType;
        @XmlElement(name = "MaterialOpacity")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String materialOpacity;
        @XmlElement(name = "PatternStyle")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String patternStyle;
        @XmlElement(name = "PerformanceRating")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected List<String> performanceRating;
        @XmlElement(name = "PocketDescription")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String pocketDescription;
        @XmlElement(name = "Season")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String season;
        @XmlElement(name = "ShaftHeight")
        protected StringLengthOptionalDimension shaftHeight;
        @XmlElement(name = "ShaftWidth")
        protected StringLengthOptionalDimension shaftWidth;
        @XmlElement(name = "ShaftDiameter")
        protected StringLengthOptionalDimension shaftDiameter;
        @XmlElement(name = "SpecialSizeType")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String specialSizeType;
        @XmlElement(name = "SoleMaterial", required = true)
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String soleMaterial;
        @XmlElement(name = "SpecialFeatures")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected List<String> specialFeatures;
        @XmlElement(name = "SpecificUses")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected List<String> specificUses;
        @XmlElement(name = "Character")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String character;
        @XmlElement(name = "ToeShape")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String toeShape;
        @XmlElement(name = "WaistSize")
        protected ClothingSizeDimension waistSize;
        @XmlElement(name = "WaistStyle")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String waistStyle;
        @XmlElement(name = "WheelType")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String wheelType;
        @XmlElement(name = "WaterResistanceLevel")
        protected String waterResistanceLevel;
        @XmlElement(name = "SafetyWarning")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String safetyWarning;
        @XmlElement(name = "ManufacturerWarrantyType")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String manufacturerWarrantyType;
        @XmlElement(name = "MfrWarrantyDescriptionLabor")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String mfrWarrantyDescriptionLabor;
        @XmlElement(name = "MfrWarrantyDescriptionParts")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String mfrWarrantyDescriptionParts;
        @XmlElement(name = "SellerWarrantyDescription")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String sellerWarrantyDescription;
        @XmlElement(name = "NumberOfItems")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger numberOfItems;
        @XmlElement(name = "ItemDisplayWeight")
        protected WeightDimension itemDisplayWeight;
        @XmlElement(name = "ItemDisplayVolume")
        protected VolumeDimension itemDisplayVolume;
        @XmlElement(name = "ItemDisplayLength")
        protected LengthDimension itemDisplayLength;

        /**
         * Gets the value of the countryOfOrigin property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountryOfOrigin() {
            return countryOfOrigin;
        }

        /**
         * Sets the value of the countryOfOrigin property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountryOfOrigin(String value) {
            this.countryOfOrigin = value;
        }

        /**
         * Gets the value of the colorMap property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getColorMap() {
            return colorMap;
        }

        /**
         * Sets the value of the colorMap property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setColorMap(String value) {
            this.colorMap = value;
        }

        /**
         * Gets the value of the sizeMap property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSizeMap() {
            return sizeMap;
        }

        /**
         * Sets the value of the sizeMap property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSizeMap(String value) {
            this.sizeMap = value;
        }

        /**
         * Gets the value of the beltStyle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBeltStyle() {
            return beltStyle;
        }

        /**
         * Sets the value of the beltStyle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBeltStyle(String value) {
            this.beltStyle = value;
        }

        /**
         * Gets the value of the careInstructions property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCareInstructions() {
            return careInstructions;
        }

        /**
         * Sets the value of the careInstructions property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCareInstructions(String value) {
            this.careInstructions = value;
        }

        /**
         * Gets the value of the shoeClosureType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShoeClosureType() {
            return shoeClosureType;
        }

        /**
         * Sets the value of the shoeClosureType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShoeClosureType(String value) {
            this.shoeClosureType = value;
        }

        /**
         * Gets the value of the countryProducedIn property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountryProducedIn() {
            return countryProducedIn;
        }

        /**
         * Sets the value of the countryProducedIn property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountryProducedIn(String value) {
            this.countryProducedIn = value;
        }

        /**
         * Gets the value of the department property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the department property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDepartment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getDepartment() {
            if (department == null) {
                department = new ArrayList<String>();
            }
            return this.department;
        }

        /**
         * Gets the value of the externalTestingCertification property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the externalTestingCertification property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExternalTestingCertification().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getExternalTestingCertification() {
            if (externalTestingCertification == null) {
                externalTestingCertification = new ArrayList<String>();
            }
            return this.externalTestingCertification;
        }

        /**
         * Gets the value of the fabricType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFabricType() {
            return fabricType;
        }

        /**
         * Sets the value of the fabricType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFabricType(String value) {
            this.fabricType = value;
        }

        /**
         * Gets the value of the fabricWash property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFabricWash() {
            return fabricWash;
        }

        /**
         * Sets the value of the fabricWash property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFabricWash(String value) {
            this.fabricWash = value;
        }

        /**
         * Gets the value of the heelHeight property.
         * 
         * @return
         *     possible object is
         *     {@link LengthDimension }
         *     
         */
        public LengthDimension getHeelHeight() {
            return heelHeight;
        }

        /**
         * Sets the value of the heelHeight property.
         * 
         * @param value
         *     allowed object is
         *     {@link LengthDimension }
         *     
         */
        public void setHeelHeight(LengthDimension value) {
            this.heelHeight = value;
        }

        /**
         * Gets the value of the heelType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHeelType() {
            return heelType;
        }

        /**
         * Sets the value of the heelType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHeelType(String value) {
            this.heelType = value;
        }

        /**
         * Gets the value of the innerMaterial property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInnerMaterial() {
            return innerMaterial;
        }

        /**
         * Sets the value of the innerMaterial property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInnerMaterial(String value) {
            this.innerMaterial = value;
        }

        /**
         * Gets the value of the occasionAndLifestyle property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the occasionAndLifestyle property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOccasionAndLifestyle().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getOccasionAndLifestyle() {
            if (occasionAndLifestyle == null) {
                occasionAndLifestyle = new ArrayList<String>();
            }
            return this.occasionAndLifestyle;
        }

        /**
         * Gets the value of the materialComposition property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMaterialComposition() {
            return materialComposition;
        }

        /**
         * Sets the value of the materialComposition property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMaterialComposition(String value) {
            this.materialComposition = value;
        }

        /**
         * Gets the value of the materialType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMaterialType() {
            return materialType;
        }

        /**
         * Sets the value of the materialType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMaterialType(String value) {
            this.materialType = value;
        }

        /**
         * Gets the value of the modelNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getModelNumber() {
            return modelNumber;
        }

        /**
         * Sets the value of the modelNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setModelNumber(String value) {
            this.modelNumber = value;
        }

        /**
         * Gets the value of the modelName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getModelName() {
            return modelName;
        }

        /**
         * Sets the value of the modelName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setModelName(String value) {
            this.modelName = value;
        }

        /**
         * Gets the value of the modelYear property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getModelYear() {
            return modelYear;
        }

        /**
         * Sets the value of the modelYear property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setModelYear(BigInteger value) {
            this.modelYear = value;
        }

        /**
         * Gets the value of the outerMaterialType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOuterMaterialType() {
            return outerMaterialType;
        }

        /**
         * Sets the value of the outerMaterialType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOuterMaterialType(String value) {
            this.outerMaterialType = value;
        }

        /**
         * Gets the value of the materialOpacity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMaterialOpacity() {
            return materialOpacity;
        }

        /**
         * Sets the value of the materialOpacity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMaterialOpacity(String value) {
            this.materialOpacity = value;
        }

        /**
         * Gets the value of the patternStyle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPatternStyle() {
            return patternStyle;
        }

        /**
         * Sets the value of the patternStyle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPatternStyle(String value) {
            this.patternStyle = value;
        }

        /**
         * Gets the value of the performanceRating property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the performanceRating property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPerformanceRating().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getPerformanceRating() {
            if (performanceRating == null) {
                performanceRating = new ArrayList<String>();
            }
            return this.performanceRating;
        }

        /**
         * Gets the value of the pocketDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPocketDescription() {
            return pocketDescription;
        }

        /**
         * Sets the value of the pocketDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPocketDescription(String value) {
            this.pocketDescription = value;
        }

        /**
         * Gets the value of the season property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSeason() {
            return season;
        }

        /**
         * Sets the value of the season property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSeason(String value) {
            this.season = value;
        }

        /**
         * Gets the value of the shaftHeight property.
         * 
         * @return
         *     possible object is
         *     {@link StringLengthOptionalDimension }
         *     
         */
        public StringLengthOptionalDimension getShaftHeight() {
            return shaftHeight;
        }

        /**
         * Sets the value of the shaftHeight property.
         * 
         * @param value
         *     allowed object is
         *     {@link StringLengthOptionalDimension }
         *     
         */
        public void setShaftHeight(StringLengthOptionalDimension value) {
            this.shaftHeight = value;
        }

        /**
         * Gets the value of the shaftWidth property.
         * 
         * @return
         *     possible object is
         *     {@link StringLengthOptionalDimension }
         *     
         */
        public StringLengthOptionalDimension getShaftWidth() {
            return shaftWidth;
        }

        /**
         * Sets the value of the shaftWidth property.
         * 
         * @param value
         *     allowed object is
         *     {@link StringLengthOptionalDimension }
         *     
         */
        public void setShaftWidth(StringLengthOptionalDimension value) {
            this.shaftWidth = value;
        }

        /**
         * Gets the value of the shaftDiameter property.
         * 
         * @return
         *     possible object is
         *     {@link StringLengthOptionalDimension }
         *     
         */
        public StringLengthOptionalDimension getShaftDiameter() {
            return shaftDiameter;
        }

        /**
         * Sets the value of the shaftDiameter property.
         * 
         * @param value
         *     allowed object is
         *     {@link StringLengthOptionalDimension }
         *     
         */
        public void setShaftDiameter(StringLengthOptionalDimension value) {
            this.shaftDiameter = value;
        }

        /**
         * Gets the value of the specialSizeType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSpecialSizeType() {
            return specialSizeType;
        }

        /**
         * Sets the value of the specialSizeType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSpecialSizeType(String value) {
            this.specialSizeType = value;
        }

        /**
         * Gets the value of the soleMaterial property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSoleMaterial() {
            return soleMaterial;
        }

        /**
         * Sets the value of the soleMaterial property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSoleMaterial(String value) {
            this.soleMaterial = value;
        }

        /**
         * Gets the value of the specialFeatures property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the specialFeatures property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSpecialFeatures().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getSpecialFeatures() {
            if (specialFeatures == null) {
                specialFeatures = new ArrayList<String>();
            }
            return this.specialFeatures;
        }

        /**
         * Gets the value of the specificUses property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the specificUses property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSpecificUses().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getSpecificUses() {
            if (specificUses == null) {
                specificUses = new ArrayList<String>();
            }
            return this.specificUses;
        }

        /**
         * Gets the value of the character property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCharacter() {
            return character;
        }

        /**
         * Sets the value of the character property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCharacter(String value) {
            this.character = value;
        }

        /**
         * Gets the value of the toeShape property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getToeShape() {
            return toeShape;
        }

        /**
         * Sets the value of the toeShape property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setToeShape(String value) {
            this.toeShape = value;
        }

        /**
         * Gets the value of the waistSize property.
         * 
         * @return
         *     possible object is
         *     {@link ClothingSizeDimension }
         *     
         */
        public ClothingSizeDimension getWaistSize() {
            return waistSize;
        }

        /**
         * Sets the value of the waistSize property.
         * 
         * @param value
         *     allowed object is
         *     {@link ClothingSizeDimension }
         *     
         */
        public void setWaistSize(ClothingSizeDimension value) {
            this.waistSize = value;
        }

        /**
         * Gets the value of the waistStyle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWaistStyle() {
            return waistStyle;
        }

        /**
         * Sets the value of the waistStyle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWaistStyle(String value) {
            this.waistStyle = value;
        }

        /**
         * Gets the value of the wheelType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWheelType() {
            return wheelType;
        }

        /**
         * Sets the value of the wheelType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWheelType(String value) {
            this.wheelType = value;
        }

        /**
         * Gets the value of the waterResistanceLevel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWaterResistanceLevel() {
            return waterResistanceLevel;
        }

        /**
         * Sets the value of the waterResistanceLevel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWaterResistanceLevel(String value) {
            this.waterResistanceLevel = value;
        }

        /**
         * Gets the value of the safetyWarning property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSafetyWarning() {
            return safetyWarning;
        }

        /**
         * Sets the value of the safetyWarning property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSafetyWarning(String value) {
            this.safetyWarning = value;
        }

        /**
         * Gets the value of the manufacturerWarrantyType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getManufacturerWarrantyType() {
            return manufacturerWarrantyType;
        }

        /**
         * Sets the value of the manufacturerWarrantyType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setManufacturerWarrantyType(String value) {
            this.manufacturerWarrantyType = value;
        }

        /**
         * Gets the value of the mfrWarrantyDescriptionLabor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMfrWarrantyDescriptionLabor() {
            return mfrWarrantyDescriptionLabor;
        }

        /**
         * Sets the value of the mfrWarrantyDescriptionLabor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMfrWarrantyDescriptionLabor(String value) {
            this.mfrWarrantyDescriptionLabor = value;
        }

        /**
         * Gets the value of the mfrWarrantyDescriptionParts property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMfrWarrantyDescriptionParts() {
            return mfrWarrantyDescriptionParts;
        }

        /**
         * Sets the value of the mfrWarrantyDescriptionParts property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMfrWarrantyDescriptionParts(String value) {
            this.mfrWarrantyDescriptionParts = value;
        }

        /**
         * Gets the value of the sellerWarrantyDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSellerWarrantyDescription() {
            return sellerWarrantyDescription;
        }

        /**
         * Sets the value of the sellerWarrantyDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSellerWarrantyDescription(String value) {
            this.sellerWarrantyDescription = value;
        }

        /**
         * Gets the value of the numberOfItems property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getNumberOfItems() {
            return numberOfItems;
        }

        /**
         * Sets the value of the numberOfItems property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setNumberOfItems(BigInteger value) {
            this.numberOfItems = value;
        }

        /**
         * Gets the value of the itemDisplayWeight property.
         * 
         * @return
         *     possible object is
         *     {@link WeightDimension }
         *     
         */
        public WeightDimension getItemDisplayWeight() {
            return itemDisplayWeight;
        }

        /**
         * Sets the value of the itemDisplayWeight property.
         * 
         * @param value
         *     allowed object is
         *     {@link WeightDimension }
         *     
         */
        public void setItemDisplayWeight(WeightDimension value) {
            this.itemDisplayWeight = value;
        }

        /**
         * Gets the value of the itemDisplayVolume property.
         * 
         * @return
         *     possible object is
         *     {@link VolumeDimension }
         *     
         */
        public VolumeDimension getItemDisplayVolume() {
            return itemDisplayVolume;
        }

        /**
         * Sets the value of the itemDisplayVolume property.
         * 
         * @param value
         *     allowed object is
         *     {@link VolumeDimension }
         *     
         */
        public void setItemDisplayVolume(VolumeDimension value) {
            this.itemDisplayVolume = value;
        }

        /**
         * Gets the value of the itemDisplayLength property.
         * 
         * @return
         *     possible object is
         *     {@link LengthDimension }
         *     
         */
        public LengthDimension getItemDisplayLength() {
            return itemDisplayLength;
        }

        /**
         * Sets the value of the itemDisplayLength property.
         * 
         * @param value
         *     allowed object is
         *     {@link LengthDimension }
         *     
         */
        public void setItemDisplayLength(LengthDimension value) {
            this.itemDisplayLength = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Parentage" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="parent"/>
     *               &lt;enumeration value="child"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Size" type="{}StringNotNull" minOccurs="0"/>
     *         &lt;element name="Color" type="{}StringNotNull" minOccurs="0"/>
     *         &lt;element name="VariationTheme" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="Size"/>
     *               &lt;enumeration value="Color"/>
     *               &lt;enumeration value="SizeColor"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "parentage",
        "size",
        "color",
        "variationTheme"
    })
    public static class VariationData {

        @XmlElement(name = "Parentage")
        protected String parentage;
        @XmlElement(name = "Size")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String size;
        @XmlElement(name = "Color")
        @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
        protected String color;
        @XmlElement(name = "VariationTheme")
        protected String variationTheme;

        /**
         * Gets the value of the parentage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getParentage() {
            return parentage;
        }

        /**
         * Sets the value of the parentage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setParentage(String value) {
            this.parentage = value;
        }

        /**
         * Gets the value of the size property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSize() {
            return size;
        }

        /**
         * Sets the value of the size property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSize(String value) {
            this.size = value;
        }

        /**
         * Gets the value of the color property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getColor() {
            return color;
        }

        /**
         * Sets the value of the color property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setColor(String value) {
            this.color = value;
        }

        /**
         * Gets the value of the variationTheme property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVariationTheme() {
            return variationTheme;
        }

        /**
         * Sets the value of the variationTheme property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVariationTheme(String value) {
            this.variationTheme = value;
        }

    }

}
