//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.04 at 12:30:41 上午 CST 
//


package amazclient.xmlmodel;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TimeUnitOfMeasure.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TimeUnitOfMeasure">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="sec"/>
 *     &lt;enumeration value="min"/>
 *     &lt;enumeration value="hr"/>
 *     &lt;enumeration value="days"/>
 *     &lt;enumeration value="hours"/>
 *     &lt;enumeration value="minutes"/>
 *     &lt;enumeration value="seconds"/>
 *     &lt;enumeration value="milliseconds"/>
 *     &lt;enumeration value="microseconds"/>
 *     &lt;enumeration value="nanoseconds"/>
 *     &lt;enumeration value="picoseconds"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TimeUnitOfMeasure")
@XmlEnum
public enum TimeUnitOfMeasure {

    @XmlEnumValue("sec")
    SEC("sec"),
    @XmlEnumValue("min")
    MIN("min"),
    @XmlEnumValue("hr")
    HR("hr"),
    @XmlEnumValue("days")
    DAYS("days"),
    @XmlEnumValue("hours")
    HOURS("hours"),
    @XmlEnumValue("minutes")
    MINUTES("minutes"),
    @XmlEnumValue("seconds")
    SECONDS("seconds"),
    @XmlEnumValue("milliseconds")
    MILLISECONDS("milliseconds"),
    @XmlEnumValue("microseconds")
    MICROSECONDS("microseconds"),
    @XmlEnumValue("nanoseconds")
    NANOSECONDS("nanoseconds"),
    @XmlEnumValue("picoseconds")
    PICOSECONDS("picoseconds");
    private final String value;

    TimeUnitOfMeasure(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TimeUnitOfMeasure fromValue(String v) {
        for (TimeUnitOfMeasure c: TimeUnitOfMeasure.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
