//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.04 at 12:30:41 上午 CST 
//


package amazclient.xmlmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MinimumManufacturerWeightRecommended" type="{}WeightIntegerDimension" minOccurs="0"/>
 *         &lt;element name="MaximumManufacturerWeightRecommended" type="{}WeightIntegerDimension" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "minimumManufacturerWeightRecommended",
    "maximumManufacturerWeightRecommended"
})
@XmlRootElement(name = "WeightRecommendation")
public class WeightRecommendation {

    @XmlElement(name = "MinimumManufacturerWeightRecommended")
    protected WeightIntegerDimension minimumManufacturerWeightRecommended;
    @XmlElement(name = "MaximumManufacturerWeightRecommended")
    protected WeightIntegerDimension maximumManufacturerWeightRecommended;

    /**
     * Gets the value of the minimumManufacturerWeightRecommended property.
     * 
     * @return
     *     possible object is
     *     {@link WeightIntegerDimension }
     *     
     */
    public WeightIntegerDimension getMinimumManufacturerWeightRecommended() {
        return minimumManufacturerWeightRecommended;
    }

    /**
     * Sets the value of the minimumManufacturerWeightRecommended property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeightIntegerDimension }
     *     
     */
    public void setMinimumManufacturerWeightRecommended(WeightIntegerDimension value) {
        this.minimumManufacturerWeightRecommended = value;
    }

    /**
     * Gets the value of the maximumManufacturerWeightRecommended property.
     * 
     * @return
     *     possible object is
     *     {@link WeightIntegerDimension }
     *     
     */
    public WeightIntegerDimension getMaximumManufacturerWeightRecommended() {
        return maximumManufacturerWeightRecommended;
    }

    /**
     * Sets the value of the maximumManufacturerWeightRecommended property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeightIntegerDimension }
     *     
     */
    public void setMaximumManufacturerWeightRecommended(WeightIntegerDimension value) {
        this.maximumManufacturerWeightRecommended = value;
    }

}
