//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.04 at 12:30:41 上午 CST 
//


package amazclient.xmlmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WeightRecommendationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WeightRecommendationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MaximumWeightRecommendation" type="{}PositiveWeightDimension" minOccurs="0"/>
 *         &lt;element name="MinimumWeightRecommendation" type="{}PositiveWeightDimension" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WeightRecommendationType", propOrder = {
    "maximumWeightRecommendation",
    "minimumWeightRecommendation"
})
public class WeightRecommendationType {

    @XmlElement(name = "MaximumWeightRecommendation")
    protected PositiveWeightDimension maximumWeightRecommendation;
    @XmlElement(name = "MinimumWeightRecommendation")
    protected PositiveWeightDimension minimumWeightRecommendation;

    /**
     * Gets the value of the maximumWeightRecommendation property.
     * 
     * @return
     *     possible object is
     *     {@link PositiveWeightDimension }
     *     
     */
    public PositiveWeightDimension getMaximumWeightRecommendation() {
        return maximumWeightRecommendation;
    }

    /**
     * Sets the value of the maximumWeightRecommendation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositiveWeightDimension }
     *     
     */
    public void setMaximumWeightRecommendation(PositiveWeightDimension value) {
        this.maximumWeightRecommendation = value;
    }

    /**
     * Gets the value of the minimumWeightRecommendation property.
     * 
     * @return
     *     possible object is
     *     {@link PositiveWeightDimension }
     *     
     */
    public PositiveWeightDimension getMinimumWeightRecommendation() {
        return minimumWeightRecommendation;
    }

    /**
     * Sets the value of the minimumWeightRecommendation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositiveWeightDimension }
     *     
     */
    public void setMinimumWeightRecommendation(PositiveWeightDimension value) {
        this.minimumWeightRecommendation = value;
    }

}
